version: "3.7"

services:
  nginx:
    image: nginx:1.19.0-alpine
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - 80:80
    depends_on:
      - grafana

  grafana:
    image: grafana/grafana:latest
    #user: "104"
    environment:
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SMTP_ENABLED=true
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    volumes:
      - grafana:/var/lib/grafana

volumes:
  grafana:
    driver: local