version: "3.7"

services:
  nginx:
    image: nginx:1.19.0-alpine
    volumes:
      - /opt/nginx:/etc/nginx/conf.d
    ports:
      - 80:80
    depends_on:
      - grafana

  grafana:
    image: grafana/grafana:latest
    #user: "104"
    env_file:
      - .env
    volumes:
      - grafana:/var/lib/grafana

volumes:
  grafana:
    driver: local